server:
  port: ${account_service_port}
  servlet:
    context-path: /account-service
  error:
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://${db_host}:${db_port}/${db_database}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${db_ddl_aouto}
    open-in-view: false

security:
  username: jaloliddin9
  password: jshkm92952023


#user-service metirkalarini olish uchun ishlatiladi
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
    circuitbreakers:
      ebabled: true
    ratelimiters:
      enabled: true
  metrics:
    tags:
      application:
        ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests:
              true
        resilience4j:
          cicuitbreaker:
            calls:
              true

resilience4j:
  circuitbreaker:
    config:
      default:
        registerHealthIndicator: true
    instances:
      user-service:
        register-helth-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-translation-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

#      recordFailurePredicate: io.github.robwin.exception.RecordFailurePrediate