server:
  port: 8006
  servlet:
    context-path: /account-service
  error:
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investment-cloud
    username: postgres
    password: jshkm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  username: jaloliddin21
  password: jalol21