spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      #ServerWebAxchange dan so`rov yuboruvchini aniqlay olmasa exception otmsaligi uchun
      filter:
        request-rate-limiter:
          deny-empty-key: false
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
          uri: lb://user-service

        - id: file-service
          predicates:
            - Path=/file-service/**
          uri: lb://file-service

        - id: auth-service
          predicates:
            - Path=/auth-service/**
          uri: lb://auth-service

        - id: currency-service
          predicates:
            - Path=/currency-service/**
          uri: lb://currency-service

        - id: account-service
          predicates:
            - Path=/account-service/**

#          filters:
#            - StripPrefix=1
#            - name: RequestRateLimiter
#            - args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                redis-rate-limiter.requestedTokens: 1
          uri: lb://account-service

  data:
    redis:
      port: 6379
      host: localhost

