server:
  port: ${auth_service_port}
  servlet:
    context-path: /auth-service
  error:
    include-binding-errors: always

spring:
  config:
    import:
      - security.properties
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${db_host}:${db_port}/${db_database}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${db_ddl_aouto}
    open-in-view: false
  data:
    redis:
      port: ${redis_port}
      host: ${redis_host}

#user-service metirkalarini olish uchun ishlatiladi
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
    circuitbreakers:
      ebabled: true
    ratelimiters:
      enabled: true
    refresh:
      enabled: true

  metrics:
    tags:
      application:
        ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests:
              true
        resilience4j:
          cicuitbreaker:
            calls:
              true

resilience4j:
  circuitbreaker:
    config:
      default:
        registerHealthIndicator: true
    instances:
      account-service:
        register-helth-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50 #oxirgi 10 s da yuborirgan so`rovlarining 50 % failur bo`ladigan bo`lsa Circuit Breaker OPEN holatga o`tadi
        minimum-number-of-calls: 5
        automatic-translation-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s #Circuit Breaker OPEN holatda 5s bo`ladi va shundan keyin HALF_OPEN holatga o`tadi
        permitted-number-of-calls-in-half-open-state: 3 #HALF_OPEN holatda yana  marta so`rov yuboradi, agar yuborilgan so`rovlarning 50% failur bo`lsa OPEN holatga o`tadi, aks holda CLOSED holatga o`tadi
        sliding-window-size: 10 #oxirgi 10 s dagi so`rovlarga qaraydi
        sliding-window-type: TIME_BASED #2 xil bo`ladi: COUNT_BASED, TIME_BASED, agar COUNT_BASED bo`lsa oxirgi n ta so`rovga qaraydi, agar TIME_BASED bo`lsa oxirgi t vaqtdagi so`rovlarga qaraydi
      currency-service:
        register-helth-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-translation-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
#      recordFailurePredicate: io.github.robwin.exception.RecordFailurePrediate