server:
  port: ${currency_service_port}
  servlet:
    context-path: /currency-service
  error:
    include-binding-errors: always
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${db_ddl_aouto}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

