server:
  port: ${file_service_port}
  servlet:
    context-path: /file-service
  error:
    #    validationlar uchun
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://${db_host}:${db_port}/${db_database}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${db_ddl_aouto}
    open-in-view: false
  security:
    user:
      name: Jalol
      password: Jalol9
  data:
    redis:
      port: ${redis_port}
      host: ${redis_host}

  mail:
    host: smtp.gmail.com
    port: 578
    username: jabborovjalol9@gmail.com
    password: komilaxonim2020
    properties:
      smtp:
        auth: true
        starttls:
          enable: true